---
# tasks file for roles/aci_create_vrf

- name: Add a new VRF to a tenant
  aci_vrf:
    hostname: '{{ inventory_hostname }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: no
    vrf: '{{vrf_name}}'
    tenant: '{{tn_name}}'
    descr: '{{vrf_descr}}'
    policy_control_preference: enforced
    policy_control_direction: ingress
    state: present
