---
- name: Create a Snapshot
  aci_config_snapshot:
    hostname: '{{ apic_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: no
    state: present
    export_policy: config_backup
    max_count: 10
    description: Backup Created by Ansible_119
